# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=1000)),
                ('course_name', models.CharField(max_length=100)),
                ('restrict_to_timeframe', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ownership', models.CharField(choices=[('p', 'Personal'), ('d', 'Department'), ('l', 'Library')], default='p', max_length=1)),
            ],
        ),
    ]
