# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_media_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='require_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='media',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='media',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
