# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170317_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='additional_information',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='media',
            name='drop_off_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='media',
            name='enable_subtitles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='media',
            name='format',
            field=models.CharField(choices=[('i', 'Library'), ('d', 'Personal'), ('v', 'Department')], default='i', max_length=1),
        ),
        migrations.AddField(
            model_name='media',
            name='requested_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='verified_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='restrict_to_timeframe',
            field=models.BooleanField(default=False),
        ),
    ]
